name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Cambia esto si usas una rama diferente para el desarrollo

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22'  # Cambia esto si necesitas una versión diferente

      - name: Install dependencies
        run: npm install

      - name: Build with Astro
        run: npm run build  # Este comando generará la carpeta dist

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist  # Asegúrate de que esta ruta sea correcta
          publish_branch: gh-pages
