nname: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write  # Permiso para escribir en el contenido del repositorio

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build project
        run: npm run build  # Ajusta esto según tu proceso de construcción

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: gh-pages
