name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Asegúrate de que este es el nombre de tu rama principal

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22'  # O la versión que uses

      - name: Install dependencies
        run: npm install

      - name: Build with Astro
        run: npm run build  # Esto generará la carpeta dist

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: gh-pages  # Esta es la rama donde se desplegarán los archivos
