name: Deploy Astro to GitHub Pages

on:
  push:
    branches:
      - main  # Cambia a la rama que estés usando para desarrollo

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'  # Usa la versión de Node que requiera tu proyecto

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist  # Cambia esto si Astro genera el build en otra carpeta
